# tasks file for nginx
- name: Install NGINX.
  yum: name=nginx
- command: chkconfig nginx on

- name: deploy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- command: service nginx restart