---
- name: yum install epel-repease
  yum: name=epel-release state=installed

- name: add remi-repo repository
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

- name: install php 7.2
  yum: name={{ packages }} enablerepo=remi,remi-php72 state=installed
  vars:
    packages:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip

- name: deploy php.ini
  template:
    src: php.ini
    dest: /etc/php.ini